# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'YukonWildExplorerGuide' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  rn_maps_path = '../node_modules/react-native-maps' 
  pod 'react-native-google-maps', :path => rn_maps_path

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
  

        config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++20'
  
        
        config.build_settings['GCC_TREAT_WARNINGS_AS_ERRORS'] = 'NO'
  
    
        config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
  
      
        flags = config.build_settings['OTHER_CPLUSPLUSFLAGS']

      
        if flags.is_a?(String)
          flags = flags.split(' ')
        end
        
        flags ||= ['$(inherited)']
        
      
        flags = flags.reject { |f| f.include?('-Werror') }
        
    
        flags << '-Wno-error'
        
        config.build_settings['OTHER_CPLUSPLUSFLAGS'] = flags
      end
    end
  end
end
